### ISSUE TITLE
error on register page frontend

### ISSUE THREAD

**Issue by hostitor** [manikandanraji/instaclone-frontend#1]
Hi Manikandan,
I'm deployed frontend version on here : https://inastangeran.netlify.app
but after fill register form get error below :
JSON.parse: unexpected character at line 1 column 1 of the JSON data
please help me to fix it
one note about , what's the name of cloudinary unsign upload preset name must be set for this project front end on netlify ?
finest regards

**Comment by manikandanraji** [comment]
In your frontend app, change the .env value of 'REACT_APP_BACKEND_URL' to the following:

```javascript
REACT_APP_BACKEND_URL=https://backendinstaclone.herokuapp.com/api/v1
```

The upload preset value for this project on cloudinary should be 'instaclone'

**Comment by hostitor** [comment]
hello again ,
I'm set your changes , but giving "NetworkError when attempting to fetch resource." after register button press in red popup warn on top right corner of browser.

**Comment by manikandanraji** [comment]
I think the problem is with your backend application. Make sure to setup .env variables and this project uses mongodb for database, not postgresql. For mongodb, I am using mongodb atlas service

**Comment by hostitor** [comment]
hello again ,
i set all of env variables simple like picture below & use mongodb atlas but get error :
https://i.imgur.com/ozY5uAT.png

**Comment by manikandanraji** [comment]
Login to your mongodb atlas account, on the left side you will see 'Network Access'. Open network acccess and click the button that says 'ADD IP ADDRESS', it will open a modal. In the modal, click the button that says 'ALLOW ACCESS FROM ANYWHERE'. Wait for 2-3 minutes, then try to register from your frontend

**Comment by hostitor** [comment]
thanks , worked fine after changes .
